// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmx86jzPWUPAXROvJJIabTahMRkqX5yUk',
    appId: '1:854196046657:web:da15479485eb50417dafc0',
    messagingSenderId: '854196046657',
    projectId: 'fir-database-de968',
    authDomain: 'fir-database-de968.firebaseapp.com',
    storageBucket: 'fir-database-de968.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg5o2nmBHfyhNmFxnkHBpFyX0fXCVBFzg',
    appId: '1:854196046657:android:77687e80f9254aea7dafc0',
    messagingSenderId: '854196046657',
    projectId: 'fir-database-de968',
    storageBucket: 'fir-database-de968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMszEReRRAzwpl7u49MHLgdPYhhAT1zJ8',
    appId: '1:854196046657:ios:e39bd6847e2085487dafc0',
    messagingSenderId: '854196046657',
    projectId: 'fir-database-de968',
    storageBucket: 'fir-database-de968.appspot.com',
    iosBundleId: 'com.example.firebaseDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMszEReRRAzwpl7u49MHLgdPYhhAT1zJ8',
    appId: '1:854196046657:ios:e39bd6847e2085487dafc0',
    messagingSenderId: '854196046657',
    projectId: 'fir-database-de968',
    storageBucket: 'fir-database-de968.appspot.com',
    iosBundleId: 'com.example.firebaseDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmx86jzPWUPAXROvJJIabTahMRkqX5yUk',
    appId: '1:854196046657:web:ecd402680ec174187dafc0',
    messagingSenderId: '854196046657',
    projectId: 'fir-database-de968',
    authDomain: 'fir-database-de968.firebaseapp.com',
    storageBucket: 'fir-database-de968.appspot.com',
  );
}
